[package]
name = "png"
version = "0.1.0"
authors = ["cviot <viot.camille@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.82"
image = "0.23.12"

[lib]
crate-type=["cdylib"]